---
name: Trilium
version: v0.100.0.34
upstream: v0.100.0
slug: trilium
description: TriliumNext Notes is a hierarchical note taking application with focus on building large personal knowledge bases.
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

startup: services
boot: auto
init: false

map:
  - type: addon_config
    read_only: false

ingress: true
ingress_port: 80
panel_icon: mdi:wikipedia

environment:
  TRILIUM_DATA_DIR: /config
  TRILIUM_NETWORK_PORT: "8080"
  TRILIUM_NETWORK_TRUSTEDREVERSEPROXY: "uniquelocal"

ports:
  80/tcp: 80
  8080/tcp: 8080
ports_description:
  80/tcp: Ingress (nginx)
  8080/tcp: Direct Trilium (optional)

build:
  dockerfile: Dockerfile
  args:
    TRILIUM_IMAGE: "triliumnext/trilium:0.100.0"

webui: http://[HOST]:[PORT:8080]

