---
name: Trilium Next
version: v0.100.0
upstream: v0.100.0
slug: triliumnext
description: TriliumNext Notes is a hierarchical note taking application with focus on building large personal knowledge bases.
url: https://github.com/jsittner/homeassistant-addons/triliumnext
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
map:
  - type: addon_config
    read_only: false
ingress: true
ingress_port: 8080
panel_icon: mdi:wikipedia
environment:
  TRILIUM_DATA_DIR: /config
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
image: triliumnext/trilium
webui: http://[HOST]:[PORT:8080]
