name: "NGINX Reverse Proxy"
version: "1.0.25"
slug: "nginx_proxy"
description: "A simple NGINX reverse proxy for embedding or exposing local services"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
panel_icon: mdi:proxy
ingress: false
ingress_port: 8005
ports:
  8443/tcp: 8443
map:
  - config:rw
