events {}

http {
    server {
      listen 443 ssl;
      ssl_certificate /etc/ssl/certs/fullchain.pem;
      ssl_certificate_key /etc/ssl/private/privkey.pem;
    
      location / {
        proxy_pass http://192.168.10.230:8080;
        ...
        proxy_cookie_path / "/; SameSite=None; Secure; HttpOnly";
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
        add_header X-Frame-Options "ALLOWALL" always;
        add_header Content-Security-Policy "frame-ancestors *" always;

        }
    }
}
